/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'elventear' at '6/11/16 12:21 AM' with Gradle 2.13
 *
 * @author elventear, @date 6/11/16 12:21 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
