/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'elventear' at '6/11/16 12:21 AM' with Gradle 2.13
 *
 * @author elventear, @date 6/11/16 12:21 AM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
